services:
  # The Producer (Net-Producer)
  producer:
    build:
      context: ../../
      dockerfile: Dockerfile.mission
    environment:
      - MAKNOON_AGENT_MODE=1
      - MAKNOON_PASSPHRASE=producer-pass
    user: "root"
    command: ["sh", "-c", "maknoon keygen --no-password -o producer-id && sleep 3600"]
    networks:
      - net-producer

  # The Blind Relay (Net-Producer and Net-Sink)
  relay:
    build:
      context: ../../
      dockerfile: Dockerfile.mission
    environment:
      - MAKNOON_AGENT_MODE=1
      - MAKNOON_PASSPHRASE=relay-pass
    user: "root"
    # Wait after receive so we can inspect files
    command: ["sh", "-c", "maknoon keygen --no-password -o relay-id && maknoon receive --p2p --identity relay-id --trace; sleep 3600"]
    networks:
      - net-producer
      - net-sink

  # The Sink (Net-Sink)
  sink:
    build:
      context: ../../
      dockerfile: Dockerfile.mission
    environment:
      - MAKNOON_AGENT_MODE=1
      - MAKNOON_PASSPHRASE=sink-pass
    user: "root"
    # Wait after receive so we can inspect files
    command: ["sh", "-c", "maknoon keygen --no-password -o sink-id && maknoon receive --p2p --identity sink-id --trace; sleep 3600"]
    networks:
      - net-sink

networks:
  net-producer:
    internal: true
  net-sink:
    internal: true
